#!/bin/sh
BLENDER_VERSION_STRING="3.0.0"
BLENDER_PRECOMPILED_LIBS_VERSION_STRING="blender-3.0-release"
BLENDER_PYTHON_VERSION="3.9"

./build-release-precompiled-deps.sh "$BLENDER_VERSION_STRING" "$BLENDER_PRECOMPILED_LIBS_VERSION_STRING" "$BLENDER_PYTHON_VERSION"