#!/bin/sh
BLENDER_VERSION_STRING="2.93.0"
BLENDER_PRECOMPILED_LIBS_VERSION_STRING="blender-2.93-release"
BLENDER_PYTHON_VERSION="3.9"

./build-release-precompiled-deps.sh "$BLENDER_VERSION_STRING" "$BLENDER_PRECOMPILED_LIBS_VERSION_STRING" "$BLENDER_PYTHON_VERSION"