FROM vo3xel/blender-lts-python-module:2.83.5-source

# build blender full
WORKDIR /home/blender/blender-git/blender
RUN make

# copy adapted bpy cmake file
COPY ./bpy_module.cmake /home/blender/blender-git/blender/build_files/cmake/config/bpy_module.cmake
RUN make bpy

ENV PYTHONPATH="${PYTHONPATH}:/home/blender/blender-git/lib/linux_centos7_x86_64/python/lib/python3.7/site-packages"