name: Blender as python module - nightly

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file nightly.Dockerfile --tag blender-lts-python-module:$(date +%s)
